export const ORDER_SET_TYPE = "ORDER_SET_TYPE";
export const CATEROGY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEROGY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEROGY_LIST_FAIL = 'CATEGORY_LIST_FAIL';